name: push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "56192445+peikoko@users.noreply.github.com"
          git config --local user.name "peikoko"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "自动!"
          git push

